### ISSUE TITLE
Exercise more capabilities of Swim in the tutorial application

### ISSUE THREAD

**Issue by brohitbrose** [swimos/tutorial#5]
- [x] Introduce an exercise to the reader to update `swim.tutorial.DataSource` to write to more Agents than just `/unit/master`. Edit the README in `server` accordingly.

- [x] Introduce an exercise to the reader to create a `stats` value lane in `swim.tutorial.UnitAgent` that is populated by changes to `histogram`. Maybe suggest something that follows [this](https://imgur.com/CmL0D6I) skeleton. Edit the README in `server` accordingly.
- [x] Since the data entries in `histogram` are pretty boring, maybe enhance them with some measure of central tendency (e.g. mean/median) and some measure of spread (e.g. range; stdev/variance might be harder with streaming inputs but it [seems doable](https://math.stackexchange.com/questions/198336/how-to-calculate-standard-deviation-with-streaming-inputs)?) Will leave this decision to @Crista2019 ; have fun with it!

- [x] Include solutions to a new branch (or branches, if you prefer that).

- [x] In the READMEs, ask how one might change the UI code to accommodate for these server-side changes.

**Comment by Crista2019** [comment]
addressed in the *tutorial_with_exercises* branch:
- Introduce an exercise to the reader to update swim.tutorial.DataSource to **write to more Agents than just /unit/master**... 
- Introduce an exercise to the reader to **create a stats value lane in swim.tutorial.UnitAgent that is populated by changes to histogram**...

**Comment by Crista2019** [comment]
addressed in the  _tutorial_solutions_ branch:

- **Include solutions to a new branch**... (let me know if you'd prefer multiple branches, though I like the idea of one solutions branch)
-  Since the data entries in histogram are pretty boring, maybe **enhance them with some measure of central tendency and some measure of spread** (I ended up tracking the most recent 5 data points, though this can be changed to the most recent x data points if 5 is too few)

**Comment by Crista2019** [comment]
tasks left TODO:
- [x] ask @brohitbrose about what behavior should go into the logic of `histogram.didRemove((k,o) ...` to update the stats lane(s) in `swim\tutorial\UnitAgent.java` (on the tutorial_solutions branch)

- [x] make example changes to the UI code to reflect the suggested server-side changes (on the tutorial_solutions branch)

- [x] consider how to update the way in which data is randomly generated in `swim\tutorial\DataSource` --that is random yet predictable

**Comment by Crista2019** [comment]
changes on the tutorial_solutions branch I have committed today:
- all data going to the `stats_*` lanes have been consolidated and sent from histogram to one `stats ValueLane<Value>`
- all UIs have a dropdown menu to select which web agent is shown
- changes between web agents are reflected visually with different color schemes
- the data sent from DataSource to each web agent are distinct so switching between them is more interesting
- the gauge UI now links to the stats laneURI and shows mean and local mean, variance, std dev
